# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

on:
  workflow_dispatch:
    branches: ["master", "dev", "gh_actions"]
  push:
    branches: ["dev", "gh_actions"]
  pull_request:
    branches: ["dev"]

permissions:
  contents: read


jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }} python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "windows-latest"]
            python-version: [ '3.8', '3.10' ]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ENVs100py
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda install --freeze-installed pytest
          conda env export --no-builds
          pip install -U pip
          python setup.py install

#      - name: Lint
#        shell: bash -l {0}
#        run: |
#            conda install flake8
#            python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#            python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest

